hostname: "0.0.0.0"
port: 8000

debug:
  level: "info"

servers:
  letterboxd:
    command: npx
    args:
      - -y
      - mcp-remote
      - https://letterboxd-mcp-racim-d8d0da47.mcphosting.app/sse
      - --transport
      - sse-only

  tmdb:
    command: npx
    args:
      - -y
      - mcp-remote
      - https://tmdb-mcp-racim.mcphosting.app/mcp
      - --transport
      - http-only

  allocine:
    command: npx
    args:
      - -y
      - mcp-remote
      - https://allocin-mcp-racim.mcphosting.app/sse
      - --transport
      - sse-only
